name: amd

on:
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  health-check:
    runs-on: [amdgpu-mi300-x86-64]
    timeout-minutes: 5
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install PyTorch
      run: |
        python -m pip install --upgrade pip
        pip install torch --index-url https://download.pytorch.org/whl/rocm6.2
    
    - name: GPU Health Check
      run: python -c "import torch; torch.randn(5, device='cuda')"