name: CUDA Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-identity:
    runs-on: [gpumode-nvidia-arc]
    timeout-minutes: 10
    container:
      image: nvidia/cuda:12.4.0-devel-ubuntu22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pytest
        shell: bash
        run: pip install pytest

      - name: Run script
        shell: bash
        run: pytest scripts/ci_test_cuda.py

    env:
      CUDA_VISIBLE_DEVICES: 0
